"""API routers package."""

from api.routers import (
    auth,
    chat,
    commands,
    config,
    context,
    credentials,
    embedding,
    embedding_rebuild,
    episode_profiles,
    insights,
    models,
    notebooks,
    notes,
    podcasts,
    search,
    settings,
    skills,
    source_chat,
    sources,
    speaker_profiles,
    transformations,
    workflow_builder,
    workflow_templates,
    workflows,
)

__all__ = [
    "auth",
    "chat",
    "commands",
    "config",
    "context",
    "credentials",
    "embedding",
    "embedding_rebuild",
    "episode_profiles",
    "insights",
    "models",
    "notebooks",
    "notes",
    "podcasts",
    "search",
    "settings",
    "skills",
    "source_chat",
    "sources",
    "speaker_profiles",
    "transformations",
    "workflow_builder",
    "workflow_templates",
    "workflows",
]
